### ISSUE TITLE
cannot find addon in hassio-addons repository

### ISSUE THREAD

**Issue by simeneide** [hassio-addons/addon-jupyter#2]
# Problem/Motivation
I cannot find this addon in the repository https://github.com/hassio-addons/repository.

A search on "jupyter" in the github repo returns:
> We couldn’t find any code matching 'jupyter' in hassio-addons/repository

I have already added the repo in hassio, and does not show up there either.

Am I not understanding the addon structure correctly, or has it been removed in some later versions?

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/repository">hassio-addons/repository</a></strong></div><div>Community Hass.io Add-ons for Home Assistant. Contribute to hassio-addons/repository development by creating an account on GitHub.</div></blockquote>

**Comment by robmarkcole** [comment]
Believe its on the dev addon channel

**Comment by simeneide** [comment]
Hi, thanks @robmarkcole . What is this "channel"? There is no dev branch or separate repo for this that I can find? Sorry for asking very simple questions here :)

**Comment by ludeeus** [comment]
It is here <https://github.com/hassio-addons/repository-edge> but add-ons in that repo are **NOT** intended for production use, and ~~can~~ will stop working without _any_ warnings.

**Comment by frenck** [comment]
Well, in this case, it simply won't function. 
This add-on has not been released, since I cannot get is stable.

For a list of active and published add-ons, see: https://github.com/hassio-addons/repository
